-------------------------------------------------------------------------
-- Create new APP_USER
-------------------------------------------------------------------------

CREATE TABLESPACE &APP_TBS_NAME
DATAFILE '&APP_DF_PATH' 
SIZE 4096M AUTOEXTEND ON NEXT 10M 
MAXSIZE UNLIMITED
/

CREATE USER &APP_USER IDENTIFIED BY &APP_PASSWORD
DEFAULT TABLESPACE &APP_TBS_NAME
/

GRANT RESOURCE,CONNECT        TO &APP_USER;
GRANT CREATE SESSION          TO &APP_USER;
GRANT UNLIMITED TABLESPACE    TO &APP_USER;
GRANT CREATE TABLE            TO &APP_USER;
GRANT CREATE ANY TABLE        TO &APP_USER;
GRANT CREATE ANY INDEX        TO &APP_USER;
GRANT CREATE SYNONYM          TO &APP_USER;
GRANT CREATE VIEW             TO &APP_USER;
GRANT CREATE SEQUENCE         TO &APP_USER;
GRANT CREATE PROCEDURE        TO &APP_USER;
GRANT CREATE JOB              TO &APP_USER;
GRANT CREATE ANY JOB          TO &APP_USER;
/