-------------------------------------------------------------------------
-- Create new CONFIG tables
-------------------------------------------------------------------------

-- Todo: Add comments to columns
CREATE TABLE app_roles (
    role_id            NUMBER(10),
    role_name          VARCHAR2(1000),
    role_description   VARCHAR2(4000),
    date_created       DATE DEFAULT SYSDATE,
    deleted            DATE DEFAULT NULL,
    CONSTRAINT roles_pk PRIMARY KEY ( role_id ),
    CONSTRAINT unique_roles UNIQUE ( role_name )
);

CREATE TABLE app_users (
    user_id         NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 10000 INCREMENT BY 1 ),
    user_email      VARCHAR2(1000) NOT NULL,-- ensure proc stores lower case always
    user_fullname   VARCHAR2(1000) NOT NULL,
    user_password   VARCHAR2(1000) NOT NULL,
    password_salt   VARCHAR2(1000) NOT NULL,
    user_roles      NUMBER(10) NOT NULL,
    date_created    DATE DEFAULT SYSDATE,
    deleted         DATE DEFAULT NULL,
    CONSTRAINT users_pk PRIMARY KEY ( user_id ),
    CONSTRAINT unique_email UNIQUE ( user_email ),
    CONSTRAINT unique_password UNIQUE ( user_password ),
    CONSTRAINT unique_password_salt UNIQUE ( password_salt )
);

CREATE TABLE platforms (
    platform_id     NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 10000 INCREMENT BY 1 ),
    platform_name   VARCHAR2(1000) NOT NULL,-- ensure proc stores upper case always
    date_created    DATE DEFAULT SYSDATE,
    deleted         DATE DEFAULT NULL,
    CONSTRAINT platforms_pk PRIMARY KEY ( platform_id ),
    CONSTRAINT unique_platform UNIQUE ( platform_name )
);

CREATE TABLE user_sessions (
    user_session_id   NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 10000 INCREMENT BY 1 ),
    user_id           NUMBER(10) NOT NULL,
    platform_id       NUMBER(10) NOT NULL,
    guid              VARCHAR2(100) DEFAULT '0',
    CONSTRAINT user_sessions_pk PRIMARY KEY ( user_session_id ),
    CONSTRAINT fk_session_user FOREIGN KEY ( user_id )
        REFERENCES app_users ( user_id ),
    CONSTRAINT fk_session_platform FOREIGN KEY ( platform_id )
        REFERENCES platforms ( platform_id ),
    CONSTRAINT unique_session_user UNIQUE ( user_id,platform_id ),
    CONSTRAINT unique_guid UNIQUE ( guid )
);

CREATE TABLE lawyers (
    lawyer_id         NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 10000 INCREMENT BY 1 ),
    lawyer_fullname   VARCHAR2(1000) NOT NULL,
    lawyer_email      VARCHAR2(1000) NOT NULL,-- ensure proc stores lower case always
    lawyer_phone      VARCHAR2(1000) NOT NULL,
    lawyer_address    VARCHAR2(4000) NOT NULL,
    date_created      DATE DEFAULT SYSDATE,
    deleted           DATE DEFAULT NULL,
    CONSTRAINT lawyers_pk PRIMARY KEY ( lawyer_id ),
    CONSTRAINT unique_lawyer_email UNIQUE ( lawyer_email )
);

CREATE TABLE courts (
    court_id       NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 10000 INCREMENT BY 1 ),
    court_name     VARCHAR2(1000),-- ensure proc stores upper case always
    date_created   DATE DEFAULT SYSDATE,
    deleted        DATE DEFAULT NULL,
    CONSTRAINT courts_pk PRIMARY KEY ( court_id ),
    CONSTRAINT unique_court_name UNIQUE ( court_name )
);

CREATE TABLE case_types (
    case_type_id     NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 10000 INCREMENT BY 1 ),
    case_type_name   VARCHAR2(1000),-- ensure proc stores upper case always
    date_created     DATE DEFAULT SYSDATE,
    deleted          DATE DEFAULT NULL,
    CONSTRAINT case_types_pk PRIMARY KEY ( case_type_id ),
    CONSTRAINT unique_case_type_name UNIQUE ( case_type_name )
);

CREATE TABLE locations (
    location_id     NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 10000 INCREMENT BY 1 ),
    location_name   VARCHAR2(1000),-- ensure proc stores upper case always
    date_created    DATE DEFAULT SYSDATE,
    deleted         DATE DEFAULT NULL,
    CONSTRAINT locations_pk PRIMARY KEY ( location_id ),
    CONSTRAINT unique_location_name UNIQUE ( location_name )
);

CREATE TABLE proceeding_decisions ( -- 0 pending,1 adjournment,2 interim order,3 final judgement
    proceeding_decision_id     NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 10000 INCREMENT BY 1 ),
    proceeding_decision_name   VARCHAR2(1000),-- ensure proc stores upper case always
    has_next_hearing_date      NUMBER(1) NOT NULL,
    has_order_attachment       NUMBER(1) NOT NULL,
    date_created               DATE DEFAULT SYSDATE,
    deleted                    DATE DEFAULT NULL,
    CONSTRAINT decisions_pk PRIMARY KEY ( proceeding_decision_id ),
    CONSTRAINT unique_decision_name UNIQUE ( proceeding_decision_name )
);

CREATE TABLE actor_types ( --1 petitioner,2 respondent
    actor_type_id     NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 10000 INCREMENT BY 1 ),
    actor_type_name   VARCHAR2(1000) NOT NULL,
    date_created      DATE DEFAULT SYSDATE,
    deleted           DATE DEFAULT NULL,
    CONSTRAINT actor_types_pk PRIMARY KEY ( actor_type_id ),
    CONSTRAINT unique_actor_type UNIQUE ( actor_type_name )
);