-------------------------------------------------------------------------
-- Create new CONFIG tables
-------------------------------------------------------------------------

-- Todo: Add comments to columns
CREATE TABLE app_users (
    user_id         NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 10000 INCREMENT BY 1 ),
    user_email      VARCHAR2(1000) NOT NULL,-- ensure proc stores lower case always
    user_fullname   VARCHAR2(1000) NOT NULL,
    user_password   VARCHAR2(1000) NOT NULL,
    password_salt   VARCHAR2(1000) NOT NULL,
    is_sys_admin    NUMBER(1) NOT NULL,
    is_manager      NUMBER(1) NOT NULL,
    is_operator     NUMBER(1) NOT NULL,
    date_created    DATE DEFAULT SYSDATE,
    deleted         DATE DEFAULT NULL,
    CONSTRAINT users_pk PRIMARY KEY ( user_id ),
    CONSTRAINT unique_email UNIQUE ( user_email ),
    CONSTRAINT unique_password UNIQUE ( user_password ),
    CONSTRAINT unique_password_salt UNIQUE ( password_salt )
);

CREATE TABLE lawyers (
    lawyer_id         NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 10000 INCREMENT BY 1 ),
    lawyer_fullname   VARCHAR2(1000) NOT NULL,
    lawyer_email      VARCHAR2(1000) NOT NULL,-- ensure proc stores lower case always
    lawyer_phone      VARCHAR2(1000) NOT NULL,
    lawyer_address    VARCHAR2(4000) NOT NULL,
    date_created      DATE DEFAULT SYSDATE,
    deleted           DATE DEFAULT NULL,
    CONSTRAINT lawyers_pk PRIMARY KEY ( lawyer_id ),
    CONSTRAINT unique_lawyer_email UNIQUE ( lawyer_email )
);

CREATE TABLE courts (
    court_id       NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 10000 INCREMENT BY 1 ),
    court_name     VARCHAR2(1000),-- ensure proc stores upper case always
    date_created   DATE DEFAULT SYSDATE,
    deleted        DATE DEFAULT NULL,
    CONSTRAINT courts_pk PRIMARY KEY ( court_id ),
    CONSTRAINT unique_court_name UNIQUE ( court_name )
);

CREATE TABLE case_types (
    case_type_id     NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 10000 INCREMENT BY 1 ),
    case_type_name   VARCHAR2(1000),-- ensure proc stores upper case always
    date_created     DATE DEFAULT SYSDATE,
    deleted          DATE DEFAULT NULL,
    CONSTRAINT case_types_pk PRIMARY KEY ( case_type_id ),
    CONSTRAINT unique_case_type_name UNIQUE ( case_type_name )
);

CREATE TABLE locations (
    location_id     NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 10000 INCREMENT BY 1 ),
    location_name   VARCHAR2(1000),-- ensure proc stores upper case always
    date_created    DATE DEFAULT SYSDATE,
    deleted         DATE DEFAULT NULL,
    CONSTRAINT locations_pk PRIMARY KEY ( location_id ),
    CONSTRAINT unique_location_name UNIQUE ( location_name )
);

CREATE TABLE proceeding_decisions (
    proceeding_decision_id     NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 10000 INCREMENT BY 1 ),
    proceeding_decision_name   VARCHAR2(1000),-- ensure proc stores upper case always
    date_created               DATE DEFAULT SYSDATE,
    deleted                    DATE DEFAULT NULL,
    CONSTRAINT decisions_pk PRIMARY KEY ( proceeding_decision_id ),
    CONSTRAINT unique_decision_name UNIQUE ( proceeding_decision_name )
);