-------------------------------------------------------------------------
-- Create new APP tables
-------------------------------------------------------------------------

-- Todo: Add comments to columns
CREATE TABLE audit_log (
    audit_log_id     NUMBER
        GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 ),
    updated_table    VARCHAR2(4000),
    updated_row_pk   NUMBER(25),
    updated_column   VARCHAR2(4000),
    old_value        VARCHAR2(4000),
    new_value        VARCHAR2(4000),
    updated_by       NUMBER(10) NOT NULL,
    log_timestamp    TIMESTAMP DEFAULT systimestamp,
    CONSTRAINT audit_log_pk PRIMARY KEY ( audit_log_id ),
    CONSTRAINT fk_update_by_user FOREIGN KEY ( updated_by )
        REFERENCES app_users ( user_id )
);

CREATE TABLE attachments (
    attachment_id   NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 10000 INCREMENT BY 1 ),
    filename        VARCHAR2(1000) NOT NULL,
    date_created    DATE DEFAULT SYSDATE,
    deleted         DATE DEFAULT NULL,
    CONSTRAINT attachments_pk PRIMARY KEY ( attachment_id )
);

CREATE TABLE court_cases (
    case_id          NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 10000 INCREMENT BY 1 ),
    case_number      VARCHAR2(1000) NOT NULL,
    case_type_id     NUMBER(10) NOT NULL,
    court_id         NUMBER(10) NOT NULL,
    location_id      NUMBER(10) NOT NULL,
    lawyer_id        NUMBER(10) NOT NULL,
    last_update_by   NUMBER(10) NOT NULL,
    created_by       NUMBER(10) NOT NULL,
    date_created     DATE DEFAULT SYSDATE,
    deleted          DATE DEFAULT NULL,
    CONSTRAINT cases_pk PRIMARY KEY ( case_id ),
    CONSTRAINT fk_case_type FOREIGN KEY ( case_type_id )
        REFERENCES case_types ( case_type_id ),
    CONSTRAINT fk_court FOREIGN KEY ( court_id )
        REFERENCES courts ( court_id ),
    CONSTRAINT fk_location FOREIGN KEY ( location_id )
        REFERENCES locations ( location_id ),
    CONSTRAINT fk_lawyer FOREIGN KEY ( lawyer_id )
        REFERENCES lawyers ( lawyer_id ),
    CONSTRAINT fk_updated_by FOREIGN KEY ( last_update_by )
        REFERENCES app_users ( user_id ),
    CONSTRAINT fk_created_by FOREIGN KEY ( created_by )
        REFERENCES app_users ( user_id )
);

CREATE TABLE case_dates (
    case_date_id         NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 10000 INCREMENT BY 1 ),
    case_id              NUMBER(10) NOT NULL,
    case_filed_on        DATE,
    notice_received_on   DATE,
    first_hearing_on     DATE,
    last_update_by       NUMBER(10) NOT NULL,
    deleted              DATE DEFAULT NULL,
    CONSTRAINT case_dates_pk PRIMARY KEY ( case_date_id ),
    CONSTRAINT fk_court_case FOREIGN KEY ( case_id )
        REFERENCES court_cases ( case_id ),
    CONSTRAINT fk_dates_updated_by FOREIGN KEY ( last_update_by )
        REFERENCES app_users ( user_id )
);