name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore CCMS.Server/CCMS.Server.csproj
    - name: Build
      run: dotnet build CCMS.Server/CCMS.Server.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test CCMS.Tests/CCMS.Tests.csproj --configuration Release --no-restore --verbosity normal
